name: 2 - Test Connexion Azure OIDC üîê

on:
  push:
    branches:
      - main

# OBLIGATOIRE POUR L'OIDC : On autorise le robot √† demander un jeton (token)
permissions:
  id-token: write
  contents: read

jobs:
  test-azure-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Connexion √† Azure sans mot de passe (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: V√©rification de la connexion
        run: |
          echo "Connexion r√©ussie ! Voici les infos de ma souscription :"
          az account show